### ISSUE TITLE
Saved instrument reload doesn't recall keyboard split / map

### ISSUE THREAD

**Issue by lacostenycoder** [8bitbubsy/ft2-clone#2]
I set up a basic instrument where I mapped different samples to keyboard notes.
For example I made a simple drum patch with kick, hat, snare, on 3 notes on keyboard. See screenshot of mapping.

<img src="https://user-images.githubusercontent.com/6077905/74083361-2bfbda00-4a31-11ea-8698-5f0e3a461bbf.jpg" width ="220px">

But when I reload the saved instrument, the key split mappings are lost and rest to all 0s. 

What am I doing wrong?

**Comment by 8bitbubsy** [comment]
You're doing nothing wrong! In fact, it's a bug in the instrument saver routine. I am currently working on a v1.08 of the FT2 clone, and I actually fixed this without knowing this problem existed, because I have been rewriting some of those routines lately. It'll get uploaded soon'ish.

Thanks for reporting the issue.

**Comment by lacostenycoder** [comment]
Wouldn't you leave this issue open until the bug fix has been released?

**Comment by 8bitbubsy** [comment]
You're right, I'm still new to this Git thing. =)

**Comment by 8bitbubsy** [comment]
I have now pushed the code for v1.08, which among other fixes has a fix for this problem.
