### ISSUE TITLE
Sound Recording not working on Big Sur

### ISSUE THREAD

**Issue by ayskura** [8bitbubsy/ft2-clone#31]
Is there a way around this? It has to do with permissions to use audio input
also would be great a way to stop audio recording without keyboard
thank you

**Comment by 8bitbubsy** [comment]
As said said at https://16-bits.org/ft2.php:
"_On macOS Mojave and later, you can't sample audio. This is because of an issue in SDL2 where it won't ask for permission to use the selected audio input device before sampling._"

I have no idea how to work around it.

Anyway, I changed the code to allow mouse button press to stop audio sampling, but I'm not sure when I will release a new FT2 clone version.

**Comment by ayskura** [comment]
OK brother I sorted it! to record the audio input on Big Sur (I assume all apple OS who has these new microphone protection) you do as follow:
Right click on the application and chose show package, then navigate inside /content/macos and launch ft2-clone-macos which will open the terminal.
now make sure you have selected the audio input and output in the preferences, go to the "sampler" section and click record. Select mono and now... magic, mac os will ask you for permission to use the microphone! approve and here we go: you can record! 

now another small request would be a shortcut to click the sample button (CTRL+E so go to sample editor, it would be nice to have a shortcut to start the recording! and it would be great  oskip the dialogue about stereo or mono (MONO!) maybe having two shortcuts one for stereo and one for mono so to avoid having so many dialogues?)

thank you for this awesome program! <3

**Comment by 8bitbubsy** [comment]
This is not a very feasible solution...

**Comment by 8bitbubsy** [comment]
This has been fixed, I forgot to update you about it.
