### ISSUE TITLE
You won't believe what happened when I tried to open fasttracker 2 clone version 1.26

### ISSUE THREAD

**Issue by Atekuro95** [8bitbubsy/ft2-clone#7]
it gives me this.
![image](https://user-images.githubusercontent.com/22590518/85960632-62ec7100-b97b-11ea-935a-8e483acbb3fb.png)

**Comment by 8bitbubsy** [comment]
Yes I do believe it, false virus positivies have been plaguing me for a long time on my tracker clones.... I don't know what to say or what to do, because I simply can't change it. This program does _nothing_ malicious to your computer, and if you were to compile the program from the git repo with Visual Studio 2019, you'd get a binary that also tests positive for "viruses".

**Comment by 8bitbubsy** [comment]
And just think about it... why would I spend years making a clone of old trackers, just to put a virus in it? If I had evil intentions, this would be one of the least effective ways to target many people. This kind of stuff is frustrating, and it puts my tracker clones in a bad light. The 32-bit Windows version has _many more_ false virus positives...

**Comment by 8bitbubsy** [comment]
This issue should be fixed for now by not statically linking the C runtime (CRT). You can redownload it again from 16-bits.org.
